/**
 * TODO: 
 *  - make private with mutator- and getter-methods (autogenerated)?
 */
package menus.unit;

public class UnitMenuRowEntryBooleanHandler {
	public boolean join; 
	public boolean enter; 
	public boolean fire; 
	public boolean capt; 
	public boolean launch; 
	public boolean dive;
	public boolean emerge; 
	public boolean supply; 
	public boolean wait;

	public UnitMenuRowEntryBooleanHandler() {
		clear();
	}
	
	public void clear() {
		join = false;
		enter = false;
		fire = false;
		capt = false;
		launch = false;
		dive = false;
		emerge = false;
		supply = false;
		wait = false;
	}
	
	public int getNumberOfExistingRows() {
		return
			  (join ? 1 : 0)
			+ (enter ? 1 : 0)
			+ (fire ? 1 : 0)
			+ (capt ? 1 : 0)
			+ (launch ? 1 : 0)
			+ (dive ? 1 : 0)
			+ (emerge ? 1 : 0)
			+ (supply ? 1 : 0)
			+ (wait ? 1 : 0);
	}
	
	public boolean[] getAsBooleanArray() {
		return new boolean[] {
			join,
			enter,
			fire,
			capt,
			launch,
			dive,
			emerge,
			supply,
			wait
		};
	}
}